apiVersion: v1
kind: ConfigMap
metadata:
  name: byk-admin-nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;

      server_tokens off;

      location / {
        root /usr/share/nginx/html/customer-service;
        try_files $uri /index.html;
      }

      location /status {
        access_log off;
        default_type   text/plain;
        add_header Content-Type text/plain;
        return 200 "alive";
      }
    }
