apiVersion: v1
kind: ConfigMap
metadata:
  name: byk-admin-nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      return 301 https://$host$request_uri;

      server_tokens off;
      add_header Content-Security-Policy "upgrade-insecure-requests; default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://RUUTER_URL https://TIM_URL https://CUSTOMER_SERVICE_URL https://PRIV-RUUTER_URL;";


      location / {
        root /usr/share/nginx/html/customer-service;
        try_files $uri /index.html;
      }

      location /status {
        access_log off;
        default_type   text/plain;
        add_header Content-Type text/plain;
        return 200 "alive";
      }
    }
