apiVersion: v1
kind: ConfigMap
metadata:
  name: widget-nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;

        server_tokens off;
        add_header 'Access-Control-Allow-Origin' 'https://URL_WHERE_TO_WIDGET_IS_INSTALLED' always;

        location / {
            root /usr/share/nginx/html/widget;
            index index.html;
        }

        location /status {
            access_log off;
            default_type text/plain;
            add_header Content-Type text/plain;
            return 200 "alive";
        }

        location ~* \.(js|jpg|png|css)$ {
            root /usr/share/nginx/html/widget;
        }
    }
