apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter-private
spec:
  selector:
    matchLabels:
      app: byk-ruuter-private
  template:
    metadata:
      labels:
        app: byk-ruuter-private
    spec:
      containers:
        - name: byk-ruuter-private
          image: ghcr.io/buerokratt/ruuter:beta-2.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ruuter.cors.allowedOrigins
              value: http://test.buerokratt.ee:3000
          volumeMounts:
            - name: dsl
              mountPath: /byk-ruuter-priv/DSL/
            - name: urls-env
              mountPath: /usr/local/tomcat/urls.env.json
              subPath: private.urls.docker.json
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              mv /tmp/dsl-source/$DSL_PATH/* /root/DSL/ &&
              echo 'moved'
          env:
            - name: DSL_REPO
              value: {{ .Values.byk.ruuterPrivate.dsl.repo }}
            - name: DSL_PATH
              value: {{ .Values.byk.ruuterPrivate.dsl.path }}
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
