apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-admin
spec:
  selector:
    matchLabels:
      app: byk-admin
  template:
    metadata:
      labels:
        app: byk-admin
    spec:
      containers:
        - name: byk-admin
          image: riaee/byk-customer-service:18
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: admin-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: admin-nginx
          configMap:
            name: byk-admin-nginx-config
