apiVersion: apps/v1
kind: Deployment
metadata:
  name: "byk-tim"
spec:
  selector:
    matchLabels:
      app: byk-tim
  template:
    metadata:
      labels:
        app: byk-tim
    spec:
      containers:
        - name: "byk-tim"
          image: "riaee/byk-tim:07"
          ports:
            - containerPort: 8080
              name: "http"
          env:
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-tim-postgresql"
                  key: password
            - name: "OAUTH2_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: "byk-tim-env-secret"
                  key: "oauth2_client_secret"
            - name: "KEY_STORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "byk-tim-env-secret"
                  key: "jwt_integration_key_store_password"
          volumeMounts:
            - name: tomcat-config
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
      volumes:
        - name: tomcat-config
          configMap:
            name: tomcat-server-config
