apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-bot
spec:
  selector:
    matchLabels:
      app: byk-bot
  template:
    metadata:
      labels:
        app: byk-bot
    spec:
      containers:
        - name: byk-bot
          image: "rasa/rasa:3.0.13"
          args:
            - "run"
          ports:
            - containerPort: 5005
              name: http
          volumeMounts:
            - name: loba
              mountPath: /byk-chatbot/app/models/
      # TODO: Move to a separate deployment
      initContainers:
        - name: byk-train-bot
          image: "rasa/rasa:3.0.13"
          volumeMounts:
            - name: loba
              mountPath: /app
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              apt update && apt install -y git &&
              git clone https://github.com/buerokratt/Installation-Guides/ /tmp/intallation-guides &&
              echo 'downloaded' &&
              mv /tmp/intallation-guides/default-setup/chatbot-and-training/bot/loba/* /byk-chatbot-train/chatbot/ &&
              ls /app/ &&
              echo 'training' &&
              rasa train --fixed-model-name loba-model
      volumes:
        - name: loba
          emptyDir: {}
