apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruuter
spec:
  selector:
    matchLabels:
      app: ruuter
  template:
    metadata:
      labels:
        app: ruuter
    spec:
      containers:
        - name: ruuter
          image: ghcr.io/varmoh/ruuter:b1f2b6e9646f7a3a7985a5a4b871f6bd99a7c6b9
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: dsl
              mountPath: /DSL
            {{ include "tomcat.server-config" | nindent 12 }}
      initContainers:
        - name: dsl-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              mv /tmp/dsl-source/$DSL_PATH/* /root/DSL/ &&
              echo 'moved'
          env:
            - name: DSL_REPO
              value: {{ .Values.byk.ruuter.dsl.repo }}
            - name: DSL_PATH
              value: {{ .Values.byk.ruuter.dsl.path }}
      volumes:
        - name: dsl
          emptyDir: {}
