apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-dmapper
spec:
  selector:
    matchLabels:
      app: byk-dmapper
  template:
    metadata:
      labels:
        app: byk-dmapper
    spec:
      containers:
        - name: byk-dmapper
          image: ghcr.io/varmoh/datamapper:9e0675c4c57e12e3c7688d383e7f95390c3464e5
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: dsl
              mountPath: /workspace/app/views/byk/
      initContainers:
        - name: dsl-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              mv /tmp/dsl-source/$DSL_PATH/* /root/DSL/ &&
              echo 'moved'
          env:
            - name: DSL_REPO
              value: {{ .Values.byk.dmapper.dsl.repo }}
            - name: DSL_PATH
              value: {{ .Values.byk.dmapper.dsl.path }}
      volumes:
        - name: dsl
          emptyDir: {}
