apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-anonymizer-gui
spec:
  selector:
    matchLabels:
      app: byk-anonymizer-gui
  template:
    metadata:
      labels:
        app: byk-anonymizer-gui
    spec:
      containers:
        - name: byk-anonymizer-gui
          image: "ghcr.io/buerokratt/data-anonymizer:pre-alpha-1.0.1-anonymise"
          ports:
            - containerPort: 8002 # TODO: use the correct one
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
