apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-action-server
spec:
  selector:
    matchLabels:
      app: bot-action-server
  template:
    metadata:
      labels:
        app: bot-action-server
    spec:
      containers:
        - name: bot-action-server
          image: riaee/byk:bot-action-server-20220728
          args:
            - "start"
            - "--actions"
            - "actions"
          ports:
            - containerPort: 5055
              name: http
          volumeMounts:
            - name: loba
              mountPath: /app/actions
              subPath: actions
            - name: loba
              mountPath: /app/data
              subPath: data
      initContainers:
        - name: loba-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: loba
              mountPath: /root/loba
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone https://github.com/buerokratt/Installation-Guides/ /tmp/intallation-guides &&
              echo 'downloaded' &&
              mv /tmp/intallation-guides/default-setup/chatbot-and-training/bot/loba/* /root/loba/ &&
              echo 'moved'
      volumes:
        - name: loba
          emptyDir: {}
