apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-tim
spec:
  selector:
    matchLabels:
      app: byk-tim
  template:
    metadata:
      labels:
        app: byk-tim
    spec:
      containers:
        - name: byk-tim
          image: riaee/byk-tim:07
          ports:
            - containerPort: 8443
              name: http
          envFrom:
            - configMapRef:
              name: byk-env
