apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-tim
spec:
  selector:
    matchLabels:
      app: byk-tim
  template:
    metadata:
      labels:
        app: byk-tim
    spec:
      containers:
        - name: byk-tim
          image: riaee/byk-tim:07
          ports:
            - containerPort: 8443
              name: http
          envFrom:
            - configMapRef:
                name: byk-tim-env-config
            - secretRef:
                name:
          env:
            - name: "spring.datasource.password"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-tim-postgresql"
                  key: password
            - name: security.oauth2.client.client-id
              value: {{ .Values.byk.tim.env.security.oauth2.client.clientId }}
            - name: security.oauth2.client.client-secret
              valueFrom:
                secretKeyRef:
                  name: byk-tim-env-secret
                  key: oauth2_client_secret
            - name: security.oauth2.client.registered-redirect-uri
              value: {{ .Values.byk.tim.env.security.oauth2.client.registeredRedirectUri }}
            - name: security.oauth2.client.user-authorization-uri
              value: {{ .Values.byk.tim.env.security.oauth2.client.userAuthorizationUri }}
            - name: security.oauth2.client.access-token-uri
              value: {{ .Values.byk.tim.env.security.oauth2.client.accessTokenUri }}
            - name: security.oauth2.resource.jwk.key-set-uri
              value: {{ .Values.byk.tim.env.security.oauth2.resource.jwk.keySetUri }}
            - name: legacy-portal-integration.legacyUrl
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.legacyUrl }}
            - name: legacy-portal-integration.legacyPortalRefererMarker
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.legacyPortalRefererMarker }}
            - name: legacy-portal-integration.sessionCookieDomain
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.sessionCookieDomain }}
            - name: jwt-integration.signature.issuer
              value: {{ .Values.byk.tim.env.jwtIntegration.signature.issuer }}
            - name: jwt-integration.signature.key-store
              value: {{ .Values.byk.tim.env.jwtIntegration.signature.keyStore }}
            - name: jwt-integration.signature.key-store-password
              valueFrom:
                secretKeyRef:
                  name: byk-tim-env-secret
                  key: jwt_integration_key_store_password
