apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-resql
spec:
  selector:
    matchLabels:
      app: byk-resql
  template:
    metadata:
      labels:
        app: byk-resql
    spec:
      containers:
        - name: byk-resql
          image: ghcr.io/buerokratt/resql:prod-2.1.0
          ports:
            - containerPort: 8082
              name: http
          volumeMounts:
            - name: dsl
              mountPath: /workspace/app/templates/
      initContainers:
        - name: dsl-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              mv /tmp/dsl-source/$DSL_PATH/* /root/DSL/ &&
              echo 'moved'
          env:
            - name: DSL_REPO
              value: {{ .Values.byk.resql.dsl.repo }}
            - name: DSL_PATH
              value: {{ .Values.byk.resql.dsl.path }}
      volumes:
        - name: dsl
          emptyDir: {}
