apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-services-gui
spec:
  selector:
    matchLabels:
      app: byk-services-gui
  template:
    metadata:
      labels:
        app: byk-services-gui
    spec:
      containers:
        - name: byk-services-gui
          image: "ghcr.io/buerokratt/service-module:beta-1.0.0"
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: dsl
              mountPath: {{ .Values.byk.ruuter.dsl.path }}
              subPath: public/
            - name: dsl
              mountPath: {{ .Values.byk.ruuterPrivate.dsl.path }}
              subPath: private/
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 70
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: {{ .Values.byk.dsl.image.registry }}/{{ .Values.byk.dsl.image.repository }}:{{ .Values.byk.dsl.image.tag }}
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL/
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /Ruuter/public/v2/ && mkdir -p /root/DSL/public && mv /Ruuter/public/v2/* /root/DSL/public && echo 'Public DSL moved' &&
              ls -l /Ruuter/private/v2/ && mkdir -p /root/DSL/private && mv /Ruuter/private/v2/* /root/DSL/private && echo 'Private DSL moved'
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
