apiVersion: apps/v1
kind: Deployment
metadata:
  name: "byk-tim"
spec:
  selector:
    matchLabels:
      app: byk-tim
  template:
    metadata:
      labels:
        app: byk-tim
    spec:
      containers:
        - name: "byk-tim"
          image: riaee/byk-tim:07
          ports:
            - containerPort: 8443
              name: "http"
          envFrom:
            - configMapRef:
                name: "byk-tim-env-config"
            - secretRef:
                name:
          env:
            - name: "spring.datasource.password"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-tim-postgresql"
                  key: password
            - name: "security.oauth2.client.client-id"
              value: {{ .Values.byk.tim.env.security.oauth2.client.clientId | quote }}
            - name: "security.oauth2.client.client-secret"
              valueFrom:
                secretKeyRef:
                  name: "byk-tim-env-secret"
                  key: "oauth2_client_secret"
            - name: "security.oauth2.client.registered-redirect-uri"
              value: {{ .Values.byk.tim.env.security.oauth2.client.registeredRedirectUri | quote }}
            - name: "security.oauth2.client.user-authorization-uri"
              value: {{ .Values.byk.tim.env.security.oauth2.client.userAuthorizationUri | quote }}
            - name: "security.oauth2.client.access-token-uri"
              value: {{ .Values.byk.tim.env.security.oauth2.client.accessTokenUri | quote }}
            - name: "security.oauth2.resource.jwk.key-set-uri"
              value: {{ .Values.byk.tim.env.security.oauth2.resource.jwk.keySetUri | quote }}
            - name: "legacy-portal-integration.legacyUrl"
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.legacyUrl | quote }}
            - name: "legacy-portal-integration.legacyPortalRefererMarker"
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.legacyPortalRefererMarker | quote }}
            - name: "legacy-portal-integration.sessionCookieDomain"
              value: {{ .Values.byk.tim.env.legacyPortalIntegration.sessionCookieDomain | quote }}
            - name: "jwt-integration.signature.issuer"
              value: {{ .Values.byk.tim.env.jwtIntegration.signature.issuer | quote }}
            - name: "jwt-integration.signature.key-store"
              value: {{ .Values.byk.tim.env.jwtIntegration.signature.keyStore | quote }}
            - name: "jwt-integration.signature.key-store-password"
              valueFrom:
                secretKeyRef:
                  name: "byk-tim-env-secret"
                  key: "jwt_integration_key_store_password"
