apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-resql
spec:
  selector:
    matchLabels:
      app: byk-resql
  template:
    metadata:
      labels:
        app: byk-resql
    spec:
      containers:
        - name: byk-resql
          image: ghcr.io/buerokratt/resql:prod-2.1.0
          ports:
            - containerPort: 8082
              name: http
          volumeMounts:
            - name: dsl
              mountPath: {{ .Values.byk.resql.dsl.path }}
          livenessProbe:
            httpGet:
              path: /datasources
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /datasources
              port: 8082
            initialDelaySeconds: 70
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: {{ .Values.byk.dsl.image.registry }}/{{ .Values.byk.dsl.image.repository }}:{{ .Values.byk.dsl.image.tag }}
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL/
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /Resql/ && cp -r /Resql/* /root/DSL/ && echo 'moved'
      volumes:
        - name: dsl
          emptyDir: {}
