apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-backoffice-gui
spec:
  selector:
    matchLabels:
      app: byk-backoffice-gui
  template:
    metadata:
      labels:
        app: byk-backoffice-gui
    spec:
      containers:
        - name: byk-backoffice-gui
          image: "ghcr.io/buerokratt/buerokratt-chatbot:beta-1.0.0"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "http://byk-ruuter:8080"
            - name: REACT_APP_RUUTER_V1_PRIVATE_API_URL
              value: "http://byk-ruuter-private-v1:8080"
            - name: REACT_APP_RUUTER_V2_PRIVATE_API_URL
              value: "http://byk-ruuter-private:8080"
