apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruuter-private-ingress
  labels:
    name: ruuter-private-ingress
spec:
  rules:
  - host: priv-ruuter.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: byk-ruuter-private
            port:
              number: 8080
