apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: byk-admin-ingress
  labels:
    name: byk-admin-ingress
spec:
  rules:
  - host: admin.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: byk-admin
            port:
              number: 8443
