apiVersion: v1
kind: Service
metadata:
  name: byk-ruuter-private-v1
spec:
  selector:
    app: byk-ruuter-private-v1
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
