apiVersion: v1
entries:
  chat_backoffice:
  - apiVersion: v2
    created: "2023-03-09T12:50:58.281713+02:00"
    dependencies:
    - alias: tim-postgresql
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - tim-postgresql
      version: 12.2.2
    - alias: users-db
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - users-db
      version: 12.2.2
    description: A Helm chart for chat and backoffice services
    digest: 48b46d3ce204807375c9ddca1b0f129d67a0f30ad59fb5322f85306d33d96cbd
    name: chat_backoffice
    type: application
    urls:
    - chat_backoffice-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-09T12:50:58.274792+02:00"
