apiVersion: v2
name: chat_backoffice
description: A Helm chart for Kubernetes

type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 12.2.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - timPostgresql
    alias: tim-postgresql
  - name: postgresql
    version: 12.2.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - users-db
    alias: usersDB
