imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

byk:
  ruuter:
    dsl:
      repo: https://github.com/buerokratt/Ruuter.git
      path: DSL
  ruuterPrivate:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/Ruuter.private
  resql:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/Resql
  tim:
    env:
      security:
        allowlist:
          jwt: byk-public-ruuter,byk-private-ruuter,byk-dmapper,byk-widget,byk-customer-service,byk-resql
        oauth2:
          client:
            clientId: tara_client_id
            clientSecret: tara_client_secret
            registeredRedirectUri: https://tim.byk.buerokratt.ee/authenticate
            userAuthorizationUri: https://tara-test.ria.ee/oidc/authorize
            accessTokenUri: https://tara-test.ria.ee/oidc/token
          resource:
            jwk:
              keySetUri: https://tara-test.ria.ee/oidc/jwks
      auth:
        success:
          redirect:
            whitelist: https://admin.byk.buerokratt.ee/auth/callback,https://byk.buerokratt.ee,https://byk.buerokratt.ee/auth/callback,https://admin.byk.buerokratt.ee
      frontpage:
        redirect:
          url: https://admin.byk.buerokratt.ee
      headers:
        contentSecurityPolicy: upgrade-insecure-requests; default-src 'self' 'unsafe-inline' 'unsafe-eval' https://tim.byk.buerokratt.ee https://admin.byk.buerokratt.ee https://ruuter.byk.buerokratt.ee https://priv-ruuter.byk.buerokratt.ee byk-tim byk-public-ruuter byk-private-ruuter byk-customer-service; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://byk.buerokratt.ee https://admin.byk.buerokratt.ee https://tim.byk.buerokratt.ee; connect-src 'self' https://byk.buerokratt.ee https://tim.byk.buerokratt.ee https://admin.byk.buerokratt.ee https://ruuter.byk.buerokratt.ee https://priv-ruuter.byk.buerokratt.ee; frame-src 'self'; media-src 'none'
      legacyPortalIntegration:
        legacyUrl: arendus.eesti.ee
        legacyPortalRefererMarker: https://arendus.eesti.ee/portaal
        sessionCookieDomain: buerokratt.ee
      cors:
        allowedOrigins: https://byk.buerokratt.ee,https://admin.byk.buerokratt.ee,https://ruuter.byk.buerokratt.ee,https://priv-ruuter.buerokratt.ee
      jwtIntegration:
        signature:
          issuer: byk.buerokratt.ee
          keyStorePassword: safe_keystore_password
          keyStore: file:/usr/local/tomcat/jwtkeystore.jks
      spring:
        profiles:
          active: dev
      logging:
        level:
          root: INFO

tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "123"
    database: tim

users-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "01234"
    database: byk
