imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: byk.buerokratt.example.com # byk.buerokratt.ee

ingress:
  certIssuerName: letsencrypt-prod-issuer

byk:
  ruuter:
    dsl:
      repo: https://github.com/buerokratt/Ruuter.git
      path: DSL
  ruuterPrivate:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/Ruuter.private
  resql:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/Resql
  dmapper:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/DataMapper
  liquibase:
    dsl:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL.Liquibase
  widget:
    index:
      repo: https://github.com/buerokratt/Installation-Guides.git
      path: default-setup/backoffice-and-bykstack/chat-widget/index.html
  tim:
    env:
      security:
        allowlist:
          jwt: byk-public-ruuter,byk-private-ruuter,byk-dmapper,byk-widget,byk-customer-service,byk-resql
        oauth2:
          client:
            clientId: tara_client_id
            clientSecret: tara_client_secret
            scope: openid
            userAuthorizationUri: https://tara-test.ria.ee/oidc/authorize
            accessTokenUri: https://tara-test.ria.ee/oidc/token
          resource:
            jwk:
              keySetUri: https://tara-test.ria.ee/oidc/jwks
      legacyPortalIntegration:
        legacyUrl: some.example.com
        legacyPortalRefererMarker: https://some.example.com/portal
        sessionCookieDomain: buerokratt.ee
      jwtIntegration:
        signature:
          issuer: byk.buerokratt.ee
          keyStorePassword: safe_keystore_password
          keyStore: file:/usr/local/tomcat/jwtkeystore.jks
      spring:
        profiles:
          active: dev
      logging:
        level:
          root: INFO

tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "123"
    database: tim

users-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "01234"
    database: byk
